### ISSUE TITLE
first attempt at a TEI file

### ISSUE THREAD

**Issue by setriplette** [setriplette/golden_age#6]
@ebeshero @RJP43 Sorry to be a squeaky wheel, but could one of you take a look at my dama boba TEI file and see if it looks reasonable? If so I'll go on to upconverting another text.

**Comment by ebeshero** [comment]
@RJP43 Just a ping to let you know that Stacey and I met to review the file this afternoon--all's well so far!

**Comment by RJP43** [comment]
@setriplette When converted the text are you guys removing the Notes section at the end. For example in @msb81 's file there is a section of end-notes that are in English and Spanish and I am wondering if we should RegEx those or just remove them?

**Comment by setriplette** [comment]
@RJP43 Great question! Please remove all notes and critical apparatus. We are interested in the text, not the previous edition.

**Comment by RJP43** [comment]
Okay Thanks! We have a TEI XML file up... @msb81 will work on the emotion markup this evening.
